name: erp-finance-workflow
displayName: ERP财务问题处理流程
description: 处理ERP系统财务模块相关问题的标准流程
version: "1.0"
category: erp_finance

triggers:
  categories:
    - erp_finance
  keywords:
    - 财务
    - 凭证
    - 报表
    - 账务
    - 结账
    - 对账
    - 发票
    - 税务

tools:
  - erp_query_voucher
  - erp_query_account_balance
  - erp_query_financial_report
  - knowledge_search

steps:
  - id: analyze_problem
    name: 问题分析
    type: llm
    description: 分析用户描述的财务问题，提取关键信息
    prompt: |
      你是一位专业的ERP财务系统运维专家。请分析以下财务问题：
      
      问题描述：{problem_description}
      
      请提取以下信息：
      1. 问题类型（凭证/报表/结账/对账/其他）
      2. 涉及的会计期间
      3. 相关的科目或单据编号
      4. 问题的紧急程度
      5. 可能的原因分析
    output:
      - problem_type
      - accounting_period
      - related_documents
      - urgency
      - initial_analysis

  - id: query_voucher_data
    name: 查询凭证数据
    type: tool
    condition: "analyze_problem.problem_type in ['凭证', '对账']"
    tool: erp_query_voucher
    params:
      voucher_no: "{analyze_problem.related_documents}"
      period: "{analyze_problem.accounting_period}"

  - id: query_balance
    name: 查询科目余额
    type: tool
    condition: "analyze_problem.problem_type in ['报表', '结账', '对账']"
    tool: erp_query_account_balance
    params:
      account_code: "{analyze_problem.related_documents}"
      period: "{analyze_problem.accounting_period}"

  - id: search_knowledge
    name: 检索相关知识
    type: tool
    tool: knowledge_search
    params:
      query: "{problem_description}"
      category: "fault_case"
      system_type: "erp"
      limit: 5

  - id: diagnose
    name: 问题诊断
    type: llm
    description: 基于收集的信息进行问题诊断
    prompt: |
      基于以下信息，对财务问题进行诊断：
      
      问题分析：{analyze_problem.output}
      凭证数据：{query_voucher_data.result}
      科目余额：{query_balance.result}
      相关案例：{search_knowledge.result}
      
      请给出：
      1. 问题根因分析
      2. 影响范围评估
      3. 是否需要人工介入
    output:
      - root_cause
      - impact_scope
      - need_manual_intervention

  - id: generate_solution
    name: 生成解决方案
    type: llm
    description: 生成具体的解决方案和操作步骤
    prompt: |
      基于诊断结果，生成解决方案：
      
      问题诊断：{diagnose.output}
      
      请提供：
      1. 具体解决步骤（按优先级排序）
      2. 每个步骤的操作说明
      3. 注意事项和风险提示
      4. 预防措施建议
    output:
      - solution_steps
      - operation_guide
      - risk_warnings
      - prevention_tips

response_template: |
  ## ERP财务问题处理报告
  
  ### 问题概述
  - **问题类型**: {analyze_problem.problem_type}
  - **会计期间**: {analyze_problem.accounting_period}
  - **紧急程度**: {analyze_problem.urgency}
  
  ### 问题诊断
  **根因分析**: {diagnose.root_cause}
  
  **影响范围**: {diagnose.impact_scope}
  
  ### 解决方案
  {generate_solution.solution_steps}
  
  ### 操作指南
  {generate_solution.operation_guide}
  
  ### 注意事项
  {generate_solution.risk_warnings}
  
  ### 预防建议
  {generate_solution.prevention_tips}
